FROM node:22-alpine

WORKDIR /usr/src/app

# Install Angular CLI globally
RUN npm install -g @angular/cli@19.2.22

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4200

CMD ["npm", "run", "start", "--", "--poll", "2000"]
